apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner | dump }} + "/" + ${{ values.destination.repo | dump }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
